- name: Check for system required reboot.
  hosts: ubuntu
  become: true
  vars_files:
    - discord-vars.yml

  tasks:
    - name: Check for required reboot.
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Display reboot status.
      ansible.builtin.debug:
        msg: "Reboot required: {{ reboot_required_file.stat.exists }}"

    - name: Notify server requires reboot.
      community.general.discord:
        webhook_id: "{{ discord_webhook_id }}" 
        webhook_token: "{{ discord_webhook_token }}"
        avatar_url: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/ansible.png"
        content: "{{ inventory_hostname }} Requires a reboot."
      when: reboot_required_file.stat.exists == True
