- name: Reboot systems if required.
  hosts: ubuntu
  become: true
  vars_files:
    - discord-vars.yml

  tasks:
    - name: Check for required reboot.
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if required.
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists == True

    - name: Notify server was rebooted.
      community.general.discord:
        webhook_id: "{{ discord_webhook_id }}"
        webhook_token: "{{ discord_webhook_token }}"
        content: "{{ inventory_hostname }} has been rebooted."
