- name: Update and upgrade apt packages.
  hosts: ubuntu
  become: true
  vars_files:
    - discord-vars.yml
  
  tasks:
    - name: Update apt package cache and upgrade packages.
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600

    - name: Notify server requires reboot.
      community.general.discord:
        webhook_id: "{{ discord_webhook_id }}" 
        webhook_token: "{{ discord_webhook_token }}"
        avatar_url: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/ansible.png"
        content: "Packages on {{ inventory_hostname }} updated."
