- name: Update and upgrade apt packages.
  hosts: ubuntu
  become: true
  
  tasks:
    - name: Update apt package cache and upgrade packages.
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600

    - name: Check for required reboot.
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Display reboot status.
      ansible.builtin.debug:
        msg: "Reboot required: {{ reboot_required_file.stat.exists }}"

    - name: Reboot if required.
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists == True
